USE BD_TESTE
GO

CREATE TABLE TB_CLIENTE(
	CPF VARCHAR (20),
	NOME VARCHAR (250)  NOT NULL,
	SOBRENOME VARCHAR (250) NOT NULL,
	RG VARCHAR (20) NOT NULL,
	UF CHAR (2) NOT NULL,
	LOGRADOURO VARCHAR (250) NOT NULL,
	NUMERO INT,
	COMPLEMENTO VARCHAR (20),
	CIDADE CHAR (2) NOT NULL,
	ESTADO CHAR (2) NOT NULL

	CONSTRAINT PK_CPF_CLIENTE PRIMARY KEY (CPF)
);

ALTER TABLE TB_CLIENTE ADD
CONSTRAINT ALT_COMPLEMENTO DEFAULT ('NÃO POSSUI') FOR COMPLEMENTO

CREATE TABLE TB_VAGA(
	NUMERO INT,
	SETOR VARCHAR (200)
	
	CONSTRAINT PK_NUM_VAGA PRIMARY KEY (NUMERO)
);

CREATE TABLE TB_FUNCIONARIO(
	MATRICULA INT IDENTITY,
	NOME VARCHAR (250) NOT NULL,
	RG VARCHAR (20) NOT NULL,
	UF CHAR (2) NOT NULL,
	CPF VARCHAR (20) NOT NULL

	CONSTRAINT PK_MATRICULA_FUNC PRIMARY KEY (MATRICULA)
);

CREATE TABLE TB_VEICULO(
	CPF_CLIENTE VARCHAR (20),
	PLACA VARCHAR (20),
	MARCA VARCHAR (100),
	COR VARCHAR (40),
	MODELO VARCHAR (80),
	MATRICULA_FUNCIONARIO INT

	CONSTRAINT PK_CPF_CLIENTE_VEICULO PRIMARY KEY (CPF_CLIENTE, PLACA),
	CONSTRAINT FK_CPF_CLIENTE FOREIGN KEY (CPF_CLIENTE) REFERENCES TB_CLIENTE (CPF),
	CONSTRAINT FK_MATRICULA_FUNC_VEICULO FOREIGN KEY (MATRICULA_FUNCIONARIO) REFERENCES TB_FUNCIONARIO (MATRICULA)
);

CREATE TABLE TB_LOCACAO(
	PLACA_VEICULO VARCHAR (20),
	CPF_CLIENTE VARCHAR (20),
	VAGA INT,
	DATA_HORA_ENTRADA DATETIME,
	DATA_HORA_SAIDA DATETIME,
	VALOR MONEY,

	CONSTRAINT PK_PLACA_VAGA_LOCACAO PRIMARY KEY (PLACA_VEICULO, VAGA),
	CONSTRAINT FK_VAGA_VEICULO FOREIGN KEY (VAGA) REFERENCES TB_VAGA (NUMERO),
	CONSTRAINT FK_PLACA_VEICULO FOREIGN KEY (PLACA_VEICULO, CPF_CLIENTE) REFERENCES TB_VEICULO(CPF_CLIENTE, PLACA),

	CONSTRAINT CK_VALOR CHECK (VALOR > 10)
);

ALTER TABLE TB_LOCACAO ADD
CONSTRAINT DF_ENTRADA DEFAULT (GETDATE()) FOR DATA_HORA_ENTRADA
