SELECT * FROM TB_VENDAS

-- 1 - Qual o número de registros existentes na tabela ?
SELECT
COUNT(*) AS TOTAL_REGISTROS
FROM TB_VENDAS

-- 2 - Qual o acumulado da quantidade de vendas Totais?
SELECT
SUM(QUANTIDADE) AS TOTAL_PROD_VENDIDOS
FROM TB_VENDAS

-- 3 - Qual o acumulado do valor de vendas?
SELECT
SUM(VALOR_VENDA) AS VALOR_TOTAL_VENDAS
FROM TB_VENDAS

-- 4 - Qual é a média de vendas (quantidade e valor de vendas)?
SELECT
AVG(QUANTIDADE) AS QTD_MEDIA,
AVG(VALOR_VENDA) AS VALOR_VENDA_MEDIO
FROM TB_VENDAS

-- 5 - Qual o produto com maior quantidade de vendas?
SELECT TOP 1
	PRODUTO,
	SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM TB_VENDAS
GROUP BY PRODUTO
ORDER BY SUM(QUANTIDADE) DESC

-- 6 Qual o cliente que gastou mais (maior valor de venda)?
SELECT TOP 1
	NOME AS CLIENTE,
	SUM(VALOR_VENDA) AS VALOR_TOTAL_VENDA 

FROM TB_VENDAS
GROUP BY NOME
ORDER BY SUM(VALOR_VENDA) DESC

-- 7 IGUAL A 5

-- 8 Qual os dois produtos com maior lucro?
SELECT TOP 2
	PRODUTO,
	SUM(VALOR_CUSTO) AS CUSTO_TOTAL,
	SUM(VALOR_VENDA) AS VAL_VENDA_TOTAL,
	SUM(VALOR_VENDA) - SUM(VALOR_CUSTO) AS LUCRO_TOTAL
FROM TB_VENDAS
GROUP BY PRODUTO
ORDER BY LUCRO_TOTAL DESC

-- 9 - Qual o produto com menor lucro?
SELECT TOP 1
	PRODUTO,
	SUM(QUANTIDADE) AS QTD_VENDIDA,
	SUM(VALOR_CUSTO) AS CUSTO_TOTAL,
	SUM(VALOR_VENDA) AS VAL_VENDA_TOTAL,
	SUM(VALOR_VENDA) - SUM(VALOR_CUSTO) AS LUCRO_TOTAL
FROM TB_VENDAS
GROUP BY PRODUTO
ORDER BY LUCRO_TOTAL

-- 10 - Quanto cada vendedor vendeu, considerando a quantidade 
-- e o valor de venda?
SELECT 
	VENDEDOR,
	SUM(QUANTIDADE) AS 'Total de Quantidade de Vendas',
	SUM(VALOR_VENDA) AS VALOR_TOTAL_VENDIDO
FROM TB_VENDAS
GROUP BY VENDEDOR

-- 11 - Qual vendedor deu maior lucro?
SELECT
VENDEDOR,
SUM(VALOR_VENDA) - SUM(VALOR_CUSTO) AS LUCRO_TOTAL
FROM TB_VENDAS
GROUP BY VENDEDOR
ORDER BY LUCRO_TOTAL DESC

-- 12 Qual é a soma de quantidade de venda, preço de custo 
-- e preço de venda de todos os vendedores

SELECT
	VENDEDOR,
	SUM(QUANTIDADE) AS QTD_VENDA_TOTAL,
	SUM(VALOR_CUSTO) AS CUSTO_TOTAL,
	SUM(VALOR_VENDA) AS VENDA_TOTAL
FROM TB_VENDAS
GROUP BY VENDEDOR

-- 13 - Qual o lucro de cada produto?
SELECT
	PRODUTO,
	SUM(VALOR_VENDA) - SUM(VALOR_CUSTO) AS LUCRO_TOTAL
FROM TB_VENDAS
GROUP BY PRODUTO

-- 14 - Quantos produtos cada cliente comprou?
SELECT 
	NOME AS CLIENTE,
	PRODUTO,
	SUM(QUANTIDADE) AS QTD_TOTAL
FROM TB_VENDAS
GROUP BY
	NOME,
	PRODUTO
ORDER BY NOME

-- 15 - Efetue a soma de todos os valores por Produto, 
-- o lucro ordenando do maior lucro para o menor.

SELECT 
	PRODUTO,
	SUM(VALOR_VENDA),
	SUM(VALOR_VENDA) - SUM(VALOR_CUSTO) AS LUCRO_TOTAL
FROM TB_VENDAS
GROUP BY PRODUTO
ORDER BY LUCRO_TOTAL DESC
